database:
  jdbc: "jdbc:mysql://db.example.com:3306/databasename"
  user: "username"
  password: "password"
insomnia:
  enabled: true
  chance: 0.1
utility:
  anvil: true
  brewing_stand: true
  cartography_table: true
  craft: true
  ender_chest: true
  grindstone: true
  loom: true
  smithing_table: true
  stonecutter: true
  enchantment_table: true