database:
  jdbc: "jdbc:mysql://db.example.com:3306/databasename"
  user: "username"
  password: "password"

features:
  insomnia: true
  joinleave: true # Change default join/leave message
  durability_ping: true # Receive a message when a tool reach a certain durability

insomnia:
  chance: 0.1

joinleave:
  join: "[§a+§r] $player"
  leave: "[§c-§r] $player"

durability_ping:
  trigger: 10 # Any numbers between 0 and 1 will be interpreted as percentage
  warning_message: "§cYour item will break soon!"
  warning_sound: "BLOCK_ANVIL_LAND"

utility: # Access to /utility [block]
  anvil: true
  brewing_stand: true
  cartography_table: true
  craft: true
  ender_chest: true
  grindstone: true
  loom: true
  smithing_table: true
  stonecutter: true
  enchantment_table: true