database:
  jdbc: "jdbc:mysql://db.example.com:3306/databasename"
  user: "username"
  password: "password"

features:
  insomnia: true
  joinleave: true

insomnia:
  chance: 0.1

joinleave:
  join: "[§a+§r] $player"
  leave: "[§c-§r] $player"

utility:
  anvil: true
  brewing_stand: true
  cartography_table: true
  craft: true
  ender_chest: true
  grindstone: true
  loom: true
  smithing_table: true
  stonecutter: true
  enchantment_table: true